language: python
python:
  - "3.7"
git:
  depth: 1
before_install:
  - git clone https://github.com/blackwhitetony/downloader.git
install:
  - pip install -r requirements.txt
script:
  - python 1010jiajiao.py
  - python 1010jiajiaohtml5.py
